    [features]
    seeds = false
    skip-lint = false


    [registry]
    url = "https://anchor.projectserum.com"

    [provider]
    cluster = "devnet"
    wallet = "~/.config/solana/id.json"

    [scripts]
    test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

    #[programs.devnet]
    #token_attack_program = "3sM1ASvMscUm9G6XDJBQYa6SFLBxzxgaunD6WYYuzyh2"

    #[programs.localnet]
    #token_attack_program = "3sM1ASvMscUm9G6XDJBQYa6SFLBxzxgaunD6WYYuzyh2"
